### PR TITLE
Misc. Changes

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by hexylena** [comment]
Upload infrastructure + validation coming later today, hopefully.

**Comment by jmchilton** [comment]
:angel: Trying to tell me to backoff?

I'll get back to work on the client but if you want me to take a pass at the backend some day let me know. Stuff like using galaxy-lib to integrate tool logic is something I'm ideally suited to do, since I just did it on the client.

Can you update the database to include information about tool requirements - list of (name, type, version). You can either add them to the model directly or add a "metadata" json blob to revision along with a "metadata_version" field so we can migrate it over time.

Also, I'd encourage you to keep an unpacked version of the tarballs on disk. I bet we will need that at some point.

**Comment by hexylena** [comment]
hah, not even a little! If you need changes in shed, please.

I'll patch this change over to the winter-sprint branch soon, I just need to get this workflow re-created for work stuff.

> Can you update the database to include information about tool requirements - list of (name, type, version). You can either add them to the model directly or add a "metadata" json blob to revision along with a "metadata_version" field so we can migrate it over time.

You're on the wrong branch, that's already in winter-sprint.
https://github.com/erasche/shed/blob/winter-sprint/base/models.py#L131

> Also, I'd encourage you to keep an unpacked version of the tarballs on disk. I bet we will need that at some point.

I'd been going back and forth on this but if you're requesting an unpacked one that nicely solves that internal debate. We'll just keep both.

**Comment by jmchilton** [comment]
@erasche Awesome on all points, thanks!

**Pull request merged**
